package DetalleApp;

/**
* DetalleApp/DetalleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from detalle.idl
* miércoles 25 de abril de 2018 11:17:34 AM COT
*/

public final class DetalleHolder implements org.omg.CORBA.portable.Streamable
{
  public DetalleApp.Detalle value = null;

  public DetalleHolder ()
  {
  }

  public DetalleHolder (DetalleApp.Detalle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DetalleApp.DetalleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DetalleApp.DetalleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DetalleApp.DetalleHelper.type ();
  }

}
