package DetalleApp;


/**
* DetalleApp/DetallePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from detalle.idl
* miércoles 25 de abril de 2018 11:17:34 AM COT
*/

public abstract class DetallePOA extends org.omg.PortableServer.Servant
 implements DetalleApp.DetalleOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarDetalle", new java.lang.Integer (0));
    _methods.put ("consultarDetalle", new java.lang.Integer (1));
    _methods.put ("eliminarDetalle", new java.lang.Integer (2));
    _methods.put ("actualizarDetalle", new java.lang.Integer (3));
    _methods.put ("listarDetalle", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DetalleApp/Detalle/insertarDetalle
       {
         int CL_ID = in.read_long ();
         String CL_NOMBRE = in.read_wstring ();
         String CL_DIRECCION = in.read_wstring ();
         int CL_TEL = in.read_long ();
         String CL_ESTADO = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarDetalle (CL_ID, CL_NOMBRE, CL_DIRECCION, CL_TEL, CL_ESTADO);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // DetalleApp/Detalle/consultarDetalle
       {
         int CL_ID = in.read_long ();
         String CL_NOMBRE = in.read_wstring ();
         String CL_DIRECCION = in.read_wstring ();
         int CL_TEL = in.read_long ();
         String CL_ESTADO = in.read_wstring ();
         String $result = null;
         $result = this.consultarDetalle (CL_ID, CL_NOMBRE, CL_DIRECCION, CL_TEL, CL_ESTADO);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // DetalleApp/Detalle/eliminarDetalle
       {
         int CL_ID = in.read_long ();
         String CL_NOMBRE = in.read_wstring ();
         String CL_DIRECCION = in.read_wstring ();
         int CL_TEL = in.read_long ();
         String CL_ESTADO = in.read_wstring ();
         boolean $result = false;
         $result = this.eliminarDetalle (CL_ID, CL_NOMBRE, CL_DIRECCION, CL_TEL, CL_ESTADO);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // DetalleApp/Detalle/actualizarDetalle
       {
         int CL_ID = in.read_long ();
         String CL_NOMBRE = in.read_wstring ();
         String CL_DIRECCION = in.read_wstring ();
         int CL_TEL = in.read_long ();
         String CL_ESTADO = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarDetalle (CL_ID, CL_NOMBRE, CL_DIRECCION, CL_TEL, CL_ESTADO);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // DetalleApp/Detalle/listarDetalle
       {
         String $result = null;
         $result = this.listarDetalle ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // DetalleApp/Detalle/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DetalleApp/Detalle:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Detalle _this() 
  {
    return DetalleHelper.narrow(
    super._this_object());
  }

  public Detalle _this(org.omg.CORBA.ORB orb) 
  {
    return DetalleHelper.narrow(
    super._this_object(orb));
  }


} // class DetallePOA
