package DetalleApp;


/**
* DetalleApp/DetalleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from detalle.idl
* miércoles 25 de abril de 2018 11:17:34 AM COT
*/

public interface DetalleOperations 
{
  boolean insertarDetalle (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  String consultarDetalle (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  boolean eliminarDetalle (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  boolean actualizarDetalle (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  String listarDetalle ();
  void shutdown ();
} // interface DetalleOperations
