package ClienteApp;


/**
* ClienteApp/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* lunes 23 de abril de 2018 07:41:14 PM COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  String consultarCliente (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  boolean eliminarCliente (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  boolean actualizarCliente (int CL_ID, String CL_NOMBRE, String CL_DIRECCION, int CL_TEL, String CL_ESTADO);
  String listarCliente ();
  void shutdown ();
} // interface ClienteOperations
