package ClienteApp;


/**
* ClienteApp/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* lunes 23 de abril de 2018 07:41:14 PM COT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
