package ProductoApp;


/**
* ProductoApp/Producto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* lunes 21 de mayo de 2018 08:00:26 PM COT
*/

public interface Producto extends ProductoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Producto
