package ProductoApp;


/**
* ProductoApp/Producto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* jueves 26 de abril de 2018 03:57:27 AM COT
*/

public interface Producto extends ProductoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Producto
