package ProductoApp;


/**
* ProductoApp/ProductoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* jueves 26 de abril de 2018 03:57:27 AM COT
*/

public interface ProductoOperations 
{
  boolean insertarProducto (int pro_id, String pro_detalle, int pro_valor, String pro_estado);
  String consultarProducto (int pro_id, String pro_detalle, int pro_valor, String pro_estado);
  boolean eliminarProducto (int pro_id, String pro_detalle, int pro_valor, String pro_estado);
  boolean actualizarProducto (int pro_id, String pro_detalle, int pro_valor, String pro_estado);
  String listarProducto ();
  void shutdown ();
} // interface ProductoOperations
