module DetalleApp{
    interface Detalle{
        boolean insertarDetalle(in long det_fac_id,in wstring det_pro_id, in long det_cantidad, in long det_sub_total);
        wstring consultarDetalle(in long det_fac_id,in wstring det_pro_id, in long det_cantidad, in long det_sub_total);
        boolean eliminarDetalle(in long det_fac_id,in wstring det_pro_id, in long det_cantidad, in long det_sub_total);
        boolean actualizarDetalle(in long det_fac_id,in wstring det_pro_id, in long det_cantidad, in long det_sub_total);
        wstring listarDetalle();
        oneway void shutdown();
};
};
